configfile: "config/config.yaml"

SAMPLES = config["samples"]

include: "rules/simulate.smk"
include: "rules/qc.smk"
include: "rules/align.smk"
include: "rules/dedup.smk"

rule all:
    input:
        "data/NA12878_sim.bwa.read1.fastq.gz",
        "data/NA12878_sim.bwa.read2.fastq.gz",
        "data/NA12878_sim.mutations.vcf",
        "results/qc/fastqc_raw/NA12878_sim.bwa.read1_fastqc.html",
        "results/qc/fastqc_raw/NA12878_sim.bwa.read2_fastqc.html",
        "results/qc/multiqc/multiqc_report.html",
        "results/aligned/NA12878_sim.sorted.bam",
        "results/aligned/NA12878_sim.sorted.bam.bai",
        # stage 3: mark duplicates
        "results/dedup/NA12878_sim.dedup.bam",
        "results/dedup/NA12878_sim.dedup.bam.bai",
        "results/dedup/NA12878_sim.dedup.metrics.txt",
